name: Build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,] # 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: dist-artifact-${{ matrix.node-version }}
        path: |
          dist

    - name: Setup Pages
      uses: actions/configure-pages@v1
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'

  deploy:
    # only run the deploy if this is being committed to `main`
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write      
      id-token: write   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: dist-pages-artifact-14.x

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with: 
          artifact_name: github-pages
